language: node_js

node_js:
- 6.2.0

sudo: false

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test
  - NODE_ENV=production npm run deploy

install:
  - npm install

cache:
  directories:
    - node_modules
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: $HEROKU_APP

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
