language: node_js

node_js:
- 6.2.0

sudo: false

script:
  - npm run lint
  - npm run test
  - NODE_ENV=production npm run deploy

install:
  - npm install

cache:
  directories:
    - node_modules

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: $HEROKU_APP

after_success:
  - bash <(curl -s https://codecov.io/bash)
