language: node_js

node_js:
- 6.2.0

sudo: false

script:
  - npm run lint
  - npm run test
  - NODE_ENV=production npm run deploy

install:
  - npm install

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: $HEROKU_APP

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/*/lcov.info
